### ISSUE TITLE
Support Stable Rust?

### ISSUE THREAD

**Issue by zicklag** [ShisoftResearch/Lightning#4]
Hey there, this looks pretty neat! Are there any plans to support stable Rust?

**Comment by shisoft** [comment]
Hi, the reason for it is using nightly is that it uses some function provided by `core_intrinsics` for the key-value pair buffer. I can't find an alternative for now, unless rewrite most of the code to use `AtomicUsize`. I am also not sure if using it will introduce substantial overhead.
